<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "bm_products"
 *
 * Auto generated by Extension Builder 2015-12-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'BM Metaseo Test',
    'description' => 'Adds a custom page type and uses metaseo extensibility connector',
    'category' => 'plugin',
    'author' => 'Birger Stöckelmann',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];